# Generated by Django 2.0 on 2017-12-26 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost_center', models.BooleanField(default=False)),
                ('revenue_center', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepositAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cur', 'Current Account'), ('mon', 'Money'), ('inv', 'Investment')], max_length=15)),
                ('agency_number', models.CharField(max_length=30, null=True)),
                ('agency_digit', models.CharField(max_length=2, null=True)),
                ('account_number', models.CharField(max_length=30, null=True)),
                ('account_digit', models.CharField(max_length=2, null=True)),
                ('name', models.CharField(max_length=30)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.BooleanField(default=False)),
                ('supplier', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='depositaccount',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Entity'),
        ),
        migrations.AddField(
            model_name='classificationcenter',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Entity'),
        ),
    ]
