# Generated by Django 2.0 on 2017-12-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=60, null=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recurrent'), ('par', 'Parcelled')], max_length=3)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('annual', 'Annual')], max_length=15, null=True)),
                ('number_of_parcels', models.IntegerField(null=True)),
                ('document_emission_date', models.DateField(null=True)),
                ('observation', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category')),
                ('classification_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountReceivables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=60, null=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('nor', 'Normal'), ('rec', 'Recurrent'), ('par', 'Parcelled')], max_length=3)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('bimonthly', 'Bimonthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('annual', 'Annual')], max_length=15, null=True)),
                ('number_of_parcels', models.IntegerField(null=True)),
                ('document_emission_date', models.DateField(null=True)),
                ('observation', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Category')),
                ('classification_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.ClassificationCenter')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='type',
            field=models.CharField(choices=[('cur', 'Current Account'), ('mon', 'Money'), ('inv', 'Investment')], max_length=3),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='expected_deposit_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.DepositAccount'),
        ),
        migrations.AddField(
            model_name='accountreceivables',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.People'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='expected_deposit_account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.DepositAccount'),
        ),
        migrations.AddField(
            model_name='accountpayable',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.People'),
        ),
    ]
