# Generated by Django 2.0 on 2017-12-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20171229_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
