# Generated by Django 2.0 on 2018-02-10 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20171230_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositaccount',
            name='entity',
        ),
    ]
